version: '3.8'

services:
  jaeger:
    image: jaegertracing/all-in-one:1.57
    container_name: jaeger
    ports:
      - "16686:16686"  # Jaeger UI
      - "14268:14268"  # Jaeger HTTP endpoint
      - "14250:14250"  # Jaeger gRPC endpoint
      - "4318:4318"    # OTLP HTTP receiver
    environment:
      - COLLECTOR_OTLP_ENABLED=true
    networks:
      - otel-network

  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_DB: oteldb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: otelpass
      POSTGRES_HOST_AUTH_METHOD: trust
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql/data
    networks:
      - otel-network

volumes:
  postgres_data:

networks:
  otel-network:
    driver: bridge